version: "3.8"

services:
  # Qdrant Vector Database
  qdrant:
    image: qdrant/qdrant:latest
    container_name: studybuddy-qdrant
    ports:
      - "6333:6333" # HTTP API
      - "6334:6334" # gRPC API (optional)
    volumes:
      - qdrant_storage:/qdrant/storage
    environment:
      - QDRANT__SERVICE__HTTP_PORT=6333
      - QDRANT__SERVICE__GRPC_PORT=6334
    restart: unless-stopped
    networks:
      - studybuddy-network

  # StudyBuddy Backend
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: studybuddy-backend
    ports:
      - "8000:8000"
    environment:
      - QDRANT_HOST=qdrant
      - QDRANT_PORT=6333
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - PYTHONPATH=/app
    depends_on:
      - qdrant
    volumes:
      - ./backend/storage:/app/storage
      - ./docs:/app/docs
      - ./logs:/app/logs
    networks:
      - studybuddy-network
    restart: unless-stopped

  # StudyBuddy Frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: studybuddy-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - REACT_APP_API_URL=http://localhost:8000
    networks:
      - studybuddy-network
    restart: unless-stopped

volumes:
  qdrant_storage:
    driver: local
  storage-data:

networks:
  studybuddy-network:
    driver: bridge
